//> using scala "3.4.2"
//> using dep "org.scala-lang.modules::scala-parser-combinators:2.4.0"
//> using dep "org.scalameta::munit:1.2.4"
//> using dep "org.scalatest::scalatest:3.2.18"
//> using testFramework "org.scalatest.tools.Framework"
